mark: ""

model_path: "sd model path" 
lora_path:  "lora .bin path after doing things in the lora branch"

gpu: 0

# feature injection setting
start_step: 0
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [42]

# set reference image infos
ref_image_infos: {
  img1path : "image1 label",
  img2path : "image2 label",
  img3path : "image3 label"
}
target_prompt: "target prompt that describes the combination of the reference images"

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [1.0, 1.0, 1.0]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
style_fidelity: 0.5 # The larger the style_fidelity, the more like the reference concepts, range of values: [0,1]